@startuml Caravansary

left to right direction

skinparam Shadowing false
skinparam Monochrome true
skinparam PackageStyle rectangle

actor "Caravansary User" as user

package "Van" {
  usecase "Rent Out Van" as UC1
  usecase "Put on Listings" as UC2
  usecase "Rent Another Van" as UC3
}

package "Van Buddy" {
  usecase "Find a Van Buddy" as UC4
}

user --> UC1
user --> UC2
user --> UC3
user --> UC4
@enduml